const { profileCommandCallback } = require("./profile");
const { calendarCallback } = require("./calendar");
const { studentIdFormCallback } = require("./student-id-form");
const { immigrationFaqCallback } = require("./immigration-faq");
const { virtualAssistantCallback } = require("./virtual-assistant");
const { refundCallback } = require("./refund");
const { coopDocsCallback } = require("./coop-docs");
const { aboutCallback } = require("./about");
const { helpCallback } = require("./help");
const { gradesCallback } = require("./grades");
const { studentIdCallback } = require("./student-id");
const { studentAdvisorCallback } = require("./student-advisor");

module.exports.register = (app) => {
  app.command("/about", aboutCallback);
  app.command("/calendar", calendarCallback);
  app.command("/change-schedule", virtualAssistantCallback);
  app.command("/change-start-date", virtualAssistantCallback);
  app.command("/coop-docs", coopDocsCallback);
  app.command("/grades", gradesCallback);
  app.command("/help", helpCallback);
  app.command("/immigration-faq", immigrationFaqCallback);
  app.command("/loa", virtualAssistantCallback);
  app.command("/loe", virtualAssistantCallback);
  app.command("/profile", profileCommandCallback);
  app.command("/refund", refundCallback);
  app.command("/student-advisor", studentAdvisorCallback);
  app.command("/student-id-form", studentIdFormCallback);
  app.command("/student-id", studentIdCallback);
  app.command("/transcript", virtualAssistantCallback);
};
